name: ci-fin205-back-workflow
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Node 23
        uses: actions/setup-node@v4
        with:
          node-version: 23.0.0
          architecture: 'x64'
          cache: 'npm'
      - run: npm install && npm run test

