name: ci-fin205-back-workflow
on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - develop
jobs:
  check-fin-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Node 23
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.200'
      - run: dotnet test
